# Generated by Django 5.0.6 on 2024-05-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='administrador',
        ),
    ]
